name: Build Tarball

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  tar:
    name: Tarball 🛠️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix ❄️
        uses: ./.github/actions/install-nix

      - name: Set Version 🏷️
        uses: ./.github/actions/version
        id: version

      - name: Summary Headline 📝
        run: echo '## NixOS-WSL ${{ steps.version.outputs.version }}' >> $GITHUB_STEP_SUMMARY

      - name: Build Tarball 🛠️
        uses: ./.github/actions/build-wsl-tarball
        with:
          config: default
          filename: nixos.wsl

      - name: Upload Tarball 📤
        uses: actions/upload-artifact@v4
        with:
          name: tarball
          path: nixos.wsl
